---
  apiVersion: "v1"
  kind: "Pod"
  metadata:
    name: "k8s-proxy"
  spec:
    hostNetwork: true
    containers:
      -
        name: "kube-proxy"
        image: "kz8s/hyperkube-v1.2.0"
        command:
          - /hyperkube
        args:
          - proxy
          - --master=http://127.0.0.1:8080
          - --v=2
          - --resource-container=""
        securityContext:
          privileged: true
